name: mol_view_dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - pyyaml>=6.0
  - rdkit>=2023.3.1
  - pip
  - pip:
    - jinja2>=3.1.0